name: Deploy Wiki to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'wiki_output/**'
      - '.github/workflows/deploy-wiki.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create index.html
        run: |
          mkdir -p _site
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>LLM Token Analytics Library - Wiki</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      line-height: 1.6;
                      color: #24292e;
                      max-width: 1200px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f6f8fa;
                  }
                  .header {
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      padding: 40px;
                      border-radius: 10px;
                      margin-bottom: 30px;
                      text-align: center;
                  }
                  .header h1 {
                      margin: 0;
                      font-size: 2.5em;
                  }
                  .header p {
                      margin: 10px 0 0 0;
                      font-size: 1.2em;
                      opacity: 0.9;
                  }
                  .nav-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                      gap: 20px;
                      margin-bottom: 30px;
                  }
                  .nav-card {
                      background: white;
                      border: 1px solid #e1e4e8;
                      border-radius: 8px;
                      padding: 20px;
                      text-decoration: none;
                      color: inherit;
                      transition: all 0.2s ease;
                      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                  }
                  .nav-card:hover {
                      transform: translateY(-2px);
                      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
                      border-color: #0366d6;
                  }
                  .nav-card h3 {
                      margin: 0 0 10px 0;
                      color: #0366d6;
                      font-size: 1.3em;
                  }
                  .nav-card p {
                      margin: 0;
                      color: #586069;
                      font-size: 0.95em;
                  }
                  .quick-links {
                      background: white;
                      border: 1px solid #e1e4e8;
                      border-radius: 8px;
                      padding: 20px;
                      margin-bottom: 20px;
                  }
                  .quick-links h2 {
                      margin-top: 0;
                      color: #24292e;
                  }
                  .links-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                      gap: 15px;
                  }
                  .link-item {
                      display: flex;
                      align-items: center;
                      padding: 10px;
                      background: #f6f8fa;
                      border-radius: 6px;
                      text-decoration: none;
                      color: #0366d6;
                      transition: background-color 0.2s ease;
                  }
                  .link-item:hover {
                      background: #e1e4e8;
                  }
                  .footer {
                      text-align: center;
                      padding: 20px;
                      color: #586069;
                      border-top: 1px solid #e1e4e8;
                      margin-top: 40px;
                  }
                  .icon {
                      margin-right: 8px;
                      font-size: 1.2em;
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>LLM Token Analytics Library</h1>
                  <p>Comprehensive Documentation & Wiki</p>
              </div>

              <div class="nav-grid">
                  <a href="01_Overview.html" class="nav-card">
                      <h3>📖 Overview</h3>
                      <p>Learn about the library's purpose, features, and target audience</p>
                  </a>
                  <a href="02_Architecture.html" class="nav-card">
                      <h3>🏗️ Architecture</h3>
                      <p>Understand the system design, components, and technology stack</p>
                  </a>
                  <a href="03_Getting_Started.html" class="nav-card">
                      <h3>🚀 Getting Started</h3>
                      <p>Installation instructions and setup requirements</p>
                  </a>
                  <a href="04_Quick_Start.html" class="nav-card">
                      <h3>⚡ Quick Start</h3>
                      <p>Basic usage examples and common workflows</p>
                  </a>
                  <a href="05_Usage_Guide.html" class="nav-card">
                      <h3>📋 Usage Guide</h3>
                      <p>Detailed instructions for configuration and CLI usage</p>
                  </a>
                  <a href="06_API_Documentation.html" class="nav-card">
                      <h3>🔌 API Documentation</h3>
                      <p>Complete API reference and endpoint documentation</p>
                  </a>
                  <a href="07_Development.html" class="nav-card">
                      <h3>💻 Development</h3>
                      <p>Development environment setup and building from source</p>
                  </a>
                  <a href="08_Contributing.html" class="nav-card">
                      <h3>🤝 Contributing</h3>
                      <p>Guidelines for contributing to the project</p>
                  </a>
                  <a href="09_Deployment.html" class="nav-card">
                      <h3>🚢 Deployment</h3>
                      <p>Production deployment and configuration options</p>
                  </a>
                  <a href="10_Troubleshooting.html" class="nav-card">
                      <h3>🔧 Troubleshooting</h3>
                      <p>Common issues, solutions, and debugging tips</p>
                  </a>
                  <a href="11_Additional_Resources.html" class="nav-card">
                      <h3>📚 Additional Resources</h3>
                      <p>Links to external resources and community</p>
                  </a>
                  <a href="llm_token_analytics_lib_wiki.html" class="nav-card">
                      <h3>📄 Complete Wiki</h3>
                      <p>Full documentation in a single page</p>
                  </a>
              </div>

              <div class="quick-links">
                  <h2>Quick Links</h2>
                  <div class="links-grid">
                      <a href="https://github.com/aanshshah/llm_token_analytics_lib" class="link-item">
                          <span class="icon">🐙</span>
                          GitHub Repository
                      </a>
                      <a href="https://github.com/aanshshah/llm_token_analytics_lib/issues" class="link-item">
                          <span class="icon">🐛</span>
                          Report Issues
                      </a>
                      <a href="https://github.com/aanshshah/llm_token_analytics_lib/discussions" class="link-item">
                          <span class="icon">💬</span>
                          Discussions
                      </a>
                      <a href="https://github.com/aanshshah/llm_token_analytics_lib/releases" class="link-item">
                          <span class="icon">🏷️</span>
                          Releases
                      </a>
                  </div>
              </div>

              <div class="footer">
                  <p>Generated with ❤️ for the LLM Token Analytics Library</p>
                  <p>Last updated: <span id="last-updated"></span></p>
              </div>

              <script>
                  document.getElementById('last-updated').textContent = new Date().toLocaleDateString();
              </script>
          </body>
          </html>
          EOF

      - name: Convert Markdown to HTML
        run: |
          # Install pandoc for markdown conversion
          sudo apt-get update
          sudo apt-get install -y pandoc

          # Convert each markdown file to HTML with enhanced styling
          for md_file in wiki_output/*.md; do
            filename=$(basename "$md_file" .md)
            pandoc "$md_file" -o "_site/${filename}.html" \
              --standalone \
              --css="data:text/css,
                body {
                  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                  line-height: 1.6;
                  color: #24292e;
                  max-width: 900px;
                  margin: 0 auto;
                  padding: 20px;
                  background-color: #ffffff;
                }
                .header-nav {
                  background: #f6f8fa;
                  padding: 15px;
                  border-radius: 8px;
                  margin-bottom: 30px;
                  text-align: center;
                }
                .header-nav a {
                  display: inline-block;
                  margin: 0 10px;
                  padding: 8px 16px;
                  background: #0366d6;
                  color: white;
                  text-decoration: none;
                  border-radius: 5px;
                  font-size: 14px;
                }
                .header-nav a:hover {
                  background: #0256cc;
                }
                h1, h2, h3, h4, h5, h6 {
                  color: #24292e;
                  margin-top: 24px;
                  margin-bottom: 16px;
                  font-weight: 600;
                }
                h1 {
                  border-bottom: 1px solid #e1e4e8;
                  padding-bottom: 10px;
                }
                h2 {
                  border-bottom: 1px solid #e1e4e8;
                  padding-bottom: 8px;
                }
                pre {
                  background: #f6f8fa;
                  border-radius: 6px;
                  padding: 16px;
                  overflow: auto;
                  border: 1px solid #e1e4e8;
                }
                code {
                  background: #f6f8fa;
                  padding: 2px 4px;
                  border-radius: 3px;
                  font-size: 85%;
                }
                pre code {
                  background: none;
                  padding: 0;
                }
                blockquote {
                  border-left: 4px solid #dfe2e5;
                  padding-left: 16px;
                  color: #6a737d;
                  margin: 0;
                }
                table {
                  border-collapse: collapse;
                  width: 100%;
                  margin: 16px 0;
                }
                th, td {
                  border: 1px solid #e1e4e8;
                  padding: 8px 12px;
                  text-align: left;
                }
                th {
                  background: #f6f8fa;
                  font-weight: 600;
                }
                a {
                  color: #0366d6;
                  text-decoration: none;
                }
                a:hover {
                  text-decoration: underline;
                }
                .footer {
                  margin-top: 40px;
                  padding-top: 20px;
                  border-top: 1px solid #e1e4e8;
                  text-align: center;
                  color: #586069;
                  font-size: 14px;
                }
              " \
              --template=<(cat << 'TEMPLATE'
          <!DOCTYPE html>
          <html$if(lang)$ lang="$lang$"$endif$$if(dir)$ dir="$dir$"$endif$>
          <head>
            <meta charset="utf-8">
            <meta name="generator" content="pandoc">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
            $for(author-meta)$
            <meta name="author" content="$author-meta$">
            $endfor$
            $if(date-meta)$
            <meta name="dcterms.date" content="$date-meta$">
            $endif$
            $if(keywords)$
            <meta name="keywords" content="$for(keywords)$$keywords$$sep$, $endfor$">
            $endif$
            <title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
            $if(css)$
            $for(css)$
            <style>$css$</style>
            $endfor$
            $endif$
          </head>
          <body>
            <div class="header-nav">
              <a href="index.html">🏠 Home</a>
              <a href="01_Overview.html">📖 Overview</a>
              <a href="02_Architecture.html">🏗️ Architecture</a>
              <a href="03_Getting_Started.html">🚀 Getting Started</a>
              <a href="06_API_Documentation.html">🔌 API Docs</a>
              <a href="llm_token_analytics_lib_wiki.html">📄 Complete Wiki</a>
            </div>
            $body$
            <div class="footer">
              <p><a href="index.html">← Back to Wiki Home</a> | <a href="https://github.com/aanshshah/llm_token_analytics_lib">📚 GitHub Repository</a></p>
            </div>
          </body>
          </html>
          TEMPLATE
          )
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4